[[headers]]
  for = "/index.html"
  [headers.values]
    Basic-Auth = "admin:carol"

[[headers]]
  for = "/*.html"
  [headers.values]
    Basic-Auth = "client:novogene4ngs"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/auth"
  status = 200
