# 方法描述
&emsp;&emsp;以下为默认情况下流程方法描述，请老师根据实际情况加以更新。


[信息分析方法说明](src/analysis_method.readme.pdf)

[结果文件目录说明](src/Result_file_directory.pdf)

[常见问题解答](src/FAQ.pdf)

# 参考文献


- **[1] Casey AG, Michael JZ, Hongcang Gu, et al.(2013) Transcriptional and Epigenetic Dynamics during Specification of Human Embryonic Stem Cells. Cell, 153:1149-1163.**
- **[2] Schultz MD, Schmitz RJ, Ecker JR. (2012)  ‘Leveling’  the playing field for analyses of single-base resolution DNA methylomes. Trends Genet. 2012;28:583–5.  ( Weighted methylation level )**
- **[3] Lister R, Pelizzola M, Dowen RH, et al. (2009) Human DNA methylomes at base resolution show widespread epigenomic differences. Nature, 462(7271): 315-22**
- **[4] Lister R, Mukamel EA, Nery JR, Urich M, Puddifoot CA, Johnson ND, Lucero J, Huang Y, Dwork AJ, Schultz MD, et al. (2013) Global epigenomic reconfiguration during mammalian brain development. Science 341:1237905.**
- **[5] Mao X, Cai T, Olyarchuk JG, et al. (2005). Automated genome annotation and pathway identification using the KEGG Ortholotf1 (KO) as a controlled vocabulary. Bioinformatics, 21(19): 3787-93.(KOBAS)**
- **[6] Goldberg AD, Allis CD, Bernstein E, et al. (2007) Epigenetics: a landscape takes shape. Cell, 128(4): 635-8..**
- **[7] Reiner J, Pisani L, Qiao W, et al. Cytogenomic identification and long-read single molecule real-time (SMRT) sequencing of aBardet–Biedl Syndrome 9(BBS9) deletion:[J]. Npj Genomic Medicine, 2018, 3(1).**
- **[8] Kanehisa M, Araki M, Goto S, et al. (2008). KEGG for linking genomes to life and the environment. Nucleic Acids Res, 36(Database issue): D480-4.(KEGG)**
- **[9] Marta Kulis , Simon Heath , Elías Campo , José I Martín-Subero et al. (2012) Epigenomic analysis detects widespread gene-body DNA hypomethylation in chronic lymphocytic leukemia. Nature Genetics.**
- **[10] Silin Zhong, Zhangjun Fei,  Ying Shao & James J Giovannoni et al.(2013) single-base resolution methylomes of tomato fruit development reveal epigenome modifications associated with ripening. nature biotechnology.**
- **[11] Hao Feng, Karen N. Conneely, Hao Wu. (2014) A Bayesian hierarchical model to detect differentially methylated loci from single nucleotide resolution sequencing data. Nucleic Acids Research, 2014, Vol. 42, No. 8 (DSS)**
- **[12] >Qiang Song, Benjamin Decato,Jun Zhou, Andrew D. Smith et al. (2013) A Reference Methylome Database and Analysis Pipeline to Facilitate Integrative and Comparative Epigenomics . PLOS ONE**
- **[13] Lu Wang,Jun Zhang,Xingxu Huang,Jiang Liu et al. (2014) Programming and Inheritance of Parental DNA Methylomes in Mammals. Cell 157, 979–991, May 8, 2014**
- **[14] James T. Robinson, Helga Thorvaldsdóttir, Wendy Winckler, Mitchell Guttman, Eric S. Lander, Gad Getz, Jill P. Mesirov. Integrative Genomics Viewer. Nature Biotechnology 29, 24–26 (2011) (IGV)**
- **[15] Helga Thorvaldsdóttir, James T. Robinson, Jill P. Mesirov. Integrative Genomics Viewer (IGV): high-performance genomics data visualization and exploration.  Briefings in Bioinformatics 14, 178-192 (2013).( IGV )**
- **[16] Krzywinski, M. et al. Circos: an Information Aesthetic for Comparative Genomics. Genome Res (2009) 19:1639-1645 （Circos）**
- **[17] Sébastien A Smallwood, Wolf Reik , Gavin Kelsey  et al. (2014) single-cell genome-wide bisulfte sequencing for assessing epigenetic heterogeneity. nature methods **
