### SNP Statistics and Annotation
&emsp;&emsp;SNP (Single Nucleotide Polymorphism) mainly refers to the polymorphism of DNA sequences caused by single nucleotide variations at the genomic level, including transitions and transversions of individual bases.

&emsp;&emsp;The MUMmer (Version 3.23) alignment software was used to detect individual SNPs. The functions of SNPs were annotated according to the positional relationship and interaction between SNPs and genes.


<p class='mark'>Table<font face="Arial">Statistics of SNP Annotation Results</p>

```{r echo=FALSE}
library(DT)
data <- read.delim('file/06.Comparative_Genomics/snp.xls',sep='\t',header=T)
datatable(data,rownames=FALSE,extensions=c('KeyTable','Buttons','FixedColumns'),options=list(keys=T,scrollX=T,dom = 'Bfrtip',buttons = list('copy', 'print', list(extend = 'collection',buttons = c('csv', 'excel', 'pdf'),text = 'Download')),initComplete = JS("function(settings, json) {","$(this.api().table().header()).css({'background-color':'#4682B4','color': 'white'});","}")),class='nowrap')
```

- **<font face="Arial">Reference Name</font>**：Reference sequence ID
- **<font face="Arial">Sample_name</font>**：Sample ID
- **<font face="Arial">Start_syn</font>**：Synonymous mutation in start codon
- **<font face="Arial">Stop_syn</font>**：Synonymous mutation in stop codon
- **<font face="Arial">Start_nonsyn</font>**：Nonsynonymous mutation in start codon
- **<font face="Arial">Stop_nonsyn</font>**：Nonsynonymous mutation in stop codon
- **<font face="Arial">Premature_stop</font>**：Nonsense mutation, where the triplet codon at this site is mutated to a stop codon
- **<font face="Arial">Synonymous</font>**：Synonymous mutations within gene regions
- **<font face="Arial">Nonsynonymous</font>**：Nonsynonymous mutations within gene regions
- **<font face="Arial">Total_CDS_SNP</font>**：SNPs located in gene regions
- **<font face="Arial">Intergenic</font>**：SNPs located in intergenic regions
- **<font face="Arial">Total_SNP</font>**：Total SNPs in the sample

&emsp;&emsp;Result file directory：Result/06.Comparative_Genomics/SNP/

